### ISSUE TITLE
새로운 카드를 등록할 수 있는 박스 만들기

### ISSUE THREAD

**Issue by healtheloper** [healtheloper/todo-list#12]
## 예상 동작
- A가  `새로운 카드를 등록할 수 있는 박스` 에 내용을 입력하면 등록 버튼이 활성화된다.
- A가 내용을 입력후 등록을 누르면 새로운 카드가 등록된다.
- A가 카드를 등록하면 `새로운 카드를 등록할 수 있는 박스` 는 사라진다.

### task
- `새로운 카드를 등록할 수 있는 박스` 에 input value 가 생기면 등록 버튼 활성화 (색상 변경 및 disabled 해제)
- 등록 버튼을 누르면 서버에 등록 요청
- 서버에 등록 요청 이후 새로운 todos 를 바탕으로 re-rendering
- `새로운 카드를 등록할 수 있는 박스` 는 등록과 동시에 사라진다.

**Comment by healtheloper** [comment]
#11 에서 `새로운 카드를 등록할 수 있는 박스` 와 관련된 Component 를 만들고 있고
#11 이 끝나면 등록 요청 부분만 구현하면 될 것같습니다

**Comment by BB-choi** [comment]
#15 에서 만들어진 부분을 이용가능 한 부분이 있어 보여서 (등록 버튼 활성화 등),
#63 을 `dev`에 merge하고 그 이후에 작업을 시작하겠습니다.

#64 의 merge를 본 작업 후에 진행하면 될 것 같다(충돌해결)는 생각입니다!🤔
