### ISSUE TITLE
1주차 첫 번째 PR 리뷰 반영

### ISSUE THREAD

**Issue by healtheloper** [healtheloper/todo-list#20]
### PR 주소
<a href="https://github.com/codesquad-members-2022/todo-list/pull/51"> 주소 </a>

## 리뷰에서 어떤 것을 반영할지

1. `todo` 테이블에서 fk 로 활용하는 `column` 값을 명확하게 표현하기
2. db.json 의 데이터들을 모두 복수형으로 관리하기
3. import 순서 맞추기 (eslint 플러그인 써서?)
4. route 별도의 파일로 분리하기
5. router 내부에서 사용하는 함수의 파라미터 타입 통일하기
6. PUT -> PATCH 로 REST API method 수정
7. 매직넘버(혹은 enum 처럼 쓰이는 스트링 ) 별도의 파일에서 관리
8. 에러 처리관련 로직 재정비
9. 알아보기 힘든 코드( `+` 를 사용한 형변환) 를 직관적으로 변경하기
10. log 테이블에 대한 고민
  - updateAt 이 필요할지?
  - log 를 찾지 못한다면 에러?
11. lowdb 관련 update 처리를 어떻게 하는지
12. todologs 관련 routes 처리

**Comment by BB-choi** [comment]
👍
